import Link from "next/link";

export default function DemoOrganiserPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-6 rounded-3xl bg-[radial-gradient(120%_60%_at_50%_-10%,#1c3a2e_0%,#0b1520_55%,#060a10_100%)] p-6 text-white sm:p-8">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Demo · organiser view</p><h1 className="mt-2 text-3xl font-extrabold">Fundraiser dashboard</h1></div><Link href="/demo" className="text-sm font-semibold text-accent underline">Back to demo</Link></div>
      <div className="rounded-2xl border border-accent/30 bg-accent/10 p-4 text-sm text-white/75">Everything below is fictional and disabled. A real organiser can approve entrants, open rounds, record results and settle the competition.</div>
      <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white/5 p-4"><p className="text-xs font-semibold uppercase text-white/50">Confirmed entries</p><p className="mt-2 text-2xl font-extrabold">18</p><p className="mt-1 text-xs text-accent">3 awaiting approval</p></div><div className="rounded-2xl bg-white/5 p-4"><p className="text-xs font-semibold uppercase text-white/50">Raised offline</p><p className="mt-2 text-2xl font-extrabold">€600</p><p className="mt-1 text-xs text-white/45">Never handled by Last Man</p></div><div className="rounded-2xl bg-white/5 p-4"><p className="text-xs font-semibold uppercase text-white/50">Current round</p><p className="mt-2 text-2xl font-extrabold">Round 1</p><p className="mt-1 text-xs text-warning">Locks Saturday, 14:00</p></div></div>
      <section className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">People awaiting approval</h2><p className="mt-1 text-sm text-white/55">The organiser confirms offline payment before activating an entry.</p></div><button disabled className="rounded-xl bg-white/10 px-4 py-2 text-sm font-bold text-white/40">Approve all</button></div><div className="mt-4 divide-y divide-white/10 rounded-xl border border-white/10">{["Demo entrant 01", "Demo entrant 02", "Demo entrant 03"].map((name) => <div key={name} className="flex items-center justify-between px-4 py-3"><span className="font-semibold">{name}</span><span className="rounded-full bg-warning/15 px-2.5 py-1 text-xs font-bold text-warning">Awaiting payment</span></div>)}</div></section>
      <section className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-bold">Run the round</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><button disabled className="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white/40">Open gameweek</button><button disabled className="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white/40">Lock & autopick</button><button disabled className="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white/40">Record results</button></div></section>
    </div>
  );
}
